name: Trigger-All-Workflows  # 主要工作流的名称

on:
  workflow_dispatch:  # 手动触发：通过 GitHub UI 来触发
  schedule:
    - cron: 0 20 * * 5  # 北京时间星期六凌晨4点，定时触发

jobs:
    Arthur-Athena-LibWrt:
      uses: ./.github/workflows/Arthur&Athena-LibWrt.yml

    Arthur-Athena-ImmortalWrt:
      uses: ./.github/workflows/Arthur&Athena-ImmortalWrt.yml
 
    Taiyi-LibWrt:
      needs: Arthur-Athena-LibWrt
      uses: ./.github/workflows/Taiyi-LibWrt.yml

    Taiyi-ImmortalWrt:
      needs: Arthur-Athena-ImmortalWrt
      uses: ./.github/workflows/Taiyi-ImmortalWrt.yml

    x86-64-ImmortalWrt:
      uses: ./.github/workflows/x86-64-ImmortalWrt.yml

    All-Clean:
      uses: ./.github/workflows/All-Clean.yml
